name: korapay
description: "This Flutter plugin allows users to make secure payments via bank transfer or card effortlessly. Simply use the secret key provided by Korapay to enable smooth and reliable transactions within your app."
version: 0.0.2
homepage: https://github.com/Wizpna/korapay

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  uuid: ^4.4.2
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: